import 'package:hive/hive.dart';

part 'movie_detail_model.g.dart';

/// [MovieDetailModel] represents detailed information about a movie.
///
/// This model is used to store movie details in Hive for offline access.
@HiveType(typeId: 0)
class MovieDetailModel {
  /// Overview or summary of the movie.
  @HiveField(0)
  final String overview;

  /// Budget of the movie.
  @HiveField(1)
  final int? budget;

  /// Revenue generated by the movie.
  @HiveField(2)
  final int? revenue;

  /// List of spoken languages in the movie.
  @HiveField(3)
  final List<String> spokenLanguages;

  /// Constructor for creating a [MovieDetailModel] instance.
  MovieDetailModel({
    required this.overview,
    this.budget,
    this.revenue,
    required this.spokenLanguages,
  });

  /// Factory constructor for creating a [MovieDetailModel] instance from a JSON map.
  ///
  /// Parses the JSON to extract movie details including spoken languages.
  /// Limits the list of spoken languages to a maximum of 2.
  factory MovieDetailModel.fromJson(Map<String, dynamic> json) {
    List<String> languages = (json['spoken_languages'] as List?)
            ?.map((e) => e['english_name'] as String)
            .toList() ??
        <String>[];
    return MovieDetailModel(
        overview: json['overview'],
        budget: json['budget'],
        revenue: json['revenue'],
        spokenLanguages:
            languages.length > 2 ? languages.sublist(0, 2) : languages);
  }
}
