
@host = https://api.themoviedb.org/3
@accessToken=SET_YOUR_ACCESS_TOKEN_SECRET
@api_key=SET_YOUR_API_KEY


##########################################################################################################################################


### List of Trending Movies with ACCESS TOKEN
GET {{host}}/discover/movie?sort_by=popularity.desc&page=1&include_adult=false
Content-Type: application/json
Authorization: Bearer {{accessToken}}



##########################################################################################################################################


### List of Trending Movies with API KEY
GET {{host}}/discover/movie?sort_by=popularity.desc&page=1&include_adult=false&api_key={{api_key}}
Content-Type: application/json


##########################################################################################################################################


### retrieve movie detail by movieId
get https://api.themoviedb.org/3/movie/1022789
Authorization: Bearer {{accessToken}}


##########################################################################################################################################


### retrieve poster image
@poster_path=7U2m2dMSIfHx2gWXKq78Xj1weuH.jpg

GET https://image.tmdb.org/t/p/w500/{{poster_path}}


